modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/BeaconsForAll/issues"
logoFile="beaconsforall_icon.png"
[[mods]]
modId="beaconsforall"
version="${version}"
displayName="Beacons For All"
displayURL="https://github.com/TheIllusiveC4/BeaconsForAll"
authors="C4"
description='''
Allows beacons to affect more than just players, such as animals or mobs.
'''
[[dependencies.beaconsforall]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="SERVER"
[[dependencies.beaconsforall]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="SERVER"